name: Merge Dependabot PRs

on:
  check_suite:
    types:
      - completed

jobs:
  merge-me:
    name: Merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Merge Dependabot PRs
        uses: daneden/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
