name: Automatically merge GitHub Security PRs

on:
  check_suite:
    types:
      - completed

jobs:
  merge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: 'dependabot[bot]'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  merge-dependabot-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: 'dependabot-preview[bot]'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
