name: Merge Dependabot PRs

on: status

jobs:
  merge-me:
    name: Merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Debugging
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Merge Dependabot PRs
        if: ${{ github.event.state == 'success' }}
        uses: ridedott/merge-me-action@v2.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
